name: docs
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pandoc
  - pip:
    - sphinx
    - sphinxcontrib-programoutput 
    - sphinxcontrib-googleanalytics
    - nbsphinx
    - nbconvert
