package:
  name: mandelbrot-demo
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../../..

build:
  entry_points:
    - mandelbrot = mandelbrot_demo.mandelbrot:main
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: {{ PYTHON }} -m pip install ./demos/mandelbrot --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
  run:
    - python
    - pygame >=2.1
    - numpy >=1.21
    - numba >=0.55
    - dpnp
    - numba-dpex

test:
  requires:
    - pytest
  commands:
    - mandelbrot --help
    - python -m mandelbrot_demo --variant numba  --max-frames 1
    - mandelbrot --gui --max-frames 1
    - mandelbrot --no-gui --max-frames 1
  imports:
    - mandelbrot_demo
    - mandelbrot_demo.impl
    - mandelbrot_demo.impl.impl_versioner
    - mandelbrot_demo.impl.visualization
    - mandelbrot_demo.impl.arg_parser

about:
  home: https://intelpython.github.io/DPEP/main/
  license: BSD-2-Clause
  license_family: BSD
  license_file:
    - LICENSE
  summary: "Mandelbort Set demo using numpy, numba, dpnp, numba-dpex"
  description: |
    The Mandelbrot set is the set of complex numbers c for which the function f(z)=z*z + c 
    does not diverge to infinity when iterated from z=0, i.e., for which the sequence 
    f(0), f(f(0)), etc., remains bounded in absolute value. Images of the Mandelbrot set exhibit 
    an elaborate and infinitely complicated boundary that reveals progressively ever-finer 
    recursive detail at increasing magnifications

extra:
  recipe-maintainers:
    - samaid
