package:
  name: mandelbrot-demo
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  entry_points:
    - mandelbrot = mandelbrot_demo.mandelbrot:main
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
  run:
    - python
    - pygame >=2.1
    - numpy >=1.21
    - numba >=0.55
    - dpnp
    - numba-dpex

test:
  requires:
    - pytest
  commands:
    - mandelbrot --help
    - python -m mandelbrot_demo --variant numba  --max-frames 1
    - mandelbrot --gui --max-frames 1
    - mandelbrot --no-gui --max-frames 1
  imports:
    - mandelbrot_demo
    - mandelbrot_demo.impl
    - mandelbrot_demo.impl.impl_versioner
    - mandelbrot_demo.impl.visualization
    - mandelbrot_demo.impl.arg_parser

about:
  home: https://github.com/samaid
  license: BSD-2-Clause
  license_family: BSD
  license_file:
    - LICENSE
  summary: Mandelbort set demo using numpy, numba, dpnp, numba-dpex

extra:
  recipe-maintainers:
    - samaid
