name: GitHub Pages
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: echo $CONDA/bin >> $GITHUB_PATH

      - name: Sphinx
        run: |
          conda env update -f environment.yml --prune
          cd docs
          make html

      - name: GitHub Pages [main]
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html/
          destination_dir: ./main
          allow_empty_commit : true
          commit_message: ${{ github.event.head_commit.message }}
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

      - name: GitHub Pages [PR]
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event.pull_request && github.event.action != 'closed' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html/
          destination_dir: ./pull/${{ github.event.number }}
          allow_empty_commit : true
          commit_message: ${{ github.event.head_commit.message }}
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'


      - name: Unpublished pull-request docs
        if: ${{ github.event.pull_request && github.event.action == 'closed' }}
        env:
          PR_NUM: ${{ github.event.number }}
        shell: bash -l {0}
        run: |
          git remote add tokened_docs https://IntelPython:${{ secrets.GITHUB_TOKEN }}@github.com/IntelPython/DPPY.git
          git fetch tokened_docs
          git checkout --track tokened_docs/gh-pages
          echo `pwd`
          [ -d pulls/${PR_NUM} ] && git rm -rf pulls/${PR_NUM}
          git config --global user.name 'github-actions[doc-deploy-bot]'
          git config --global user.email 'github-actions[doc-deploy-bot]@users.noreply.github.com'
          git commit -m "Removing docs for closed pull request ${PR_NUM}"
          git push tokened_docs gh-pages

      - name: Comment PR with URL to published docs
        if: ${{ github.event.pull_request && github.event.action != 'closed' }}
        env:
          PR_NUM: ${{ github.event.number }}
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            View rendered docs @ https://intelpython.github.io/DPPY/pulls/${{ env.PR_NUM }}/index.html
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'

      - name: Comment PR about removal docs
        if: ${{ github.event.pull_request && github.event.action == 'closed' }}
        env:
          PR_NUM: ${{ github.event.number }}
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            Deleted docs for the PR.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
